logging:
  level:
    org.springframework.security: DEBUG
spring:
  jackson:
    default-property-inclusion: non_absent
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/webauthn
    username: root
    password: mysql
    #url: jdbc:h2:mem:webauthndemodb
  jpa:
    hibernate:
       ddl-auto: none   #used create  for 1st startup to create DDL for mysql.
  web:
    resources:
      static-locations: classpath:/META-INF/resources/webauthn
webauthn:
  relying-party-id: localhost
  relying-party-name: Example Application
  relying-party-icon: http://localhost:8080/assets/logo.png
  relying-party-origins: http://localhost:8080
  endpoints:
    registrationStartPath: /api/registration/start
    registrationAddPath: /api/registration/add
    registrationFinishPath: /api/registration/finish
    assertionStartPath: /api/assertion/start
    assertionFinishPath: /api/assertion/finish
